# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:ios)

before_all do
  # FIXME: Enable git check
  # ensure_git_status_clean
end

platform :ios do
  desc "Publish beta to TestFlight"
  lane :beta do |options|
    key_id = options[:keyID]
    issuer_id = options[:issuerID]
    key_content = options[:keyContents]

    xcodes(version: "15.4")

    app_store_connect_api_key()

    build_app(
      scheme: "Jellyfin",
      workspace: "ios/Jellyfin.xcworkspace",
      configuration: "Release"
    )
  end
end
