# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:ios)

before_all do
  # FIXME: Enable git check
  # ensure_git_status_clean
end

platform :ios do
  desc "Publish beta to TestFlight"
  lane :beta do |options|
    ensure_env_vars(
      env_vars: [
        "APP_STORE_CONNECT_API_KEY_KEY_ID",
        "APP_STORE_CONNECT_API_KEY_ISSUER_ID",
        "APP_STORE_CONNECT_API_KEY_KEY",
        "FL_CODE_SIGN_IDENTITY",
        "FL_PROVISIONING_PROFILE_SPECIFIER"
      ]
    )

    xcodes(version: "16.2")

    cocoapods(
      podfile: 'ios',
      deployment: true
    )

    app_store_connect_api_key(
      is_key_content_base64: true,
      duration: 1200,
      in_house: false
    )

    update_code_signing_settings(
      path: "ios/Jellyfin.xcodeproj",
      use_automatic_signing: false
    )

    build_app(
      scheme: "Jellyfin",
      workspace: "ios/Jellyfin.xcworkspace",
      configuration: "Release"
    )

    if options[:upload]
      upload_to_testflight()
    end
  end
end
