name: Automation

on:
  push:
    branches:
      - master
  pull_request_target:

jobs:
  labeling:
    name: Label merge conflicts
    runs-on: ubuntu-latest
    steps:
      - uses: eps1lon/actions-label-merge-conflict@1df065ebe6e3310545d4f4c4e862e43bdca146f0 # v3.0.3
        with:
          dirtyLabel: 'merge conflict'
          repoToken: ${{ secrets.JF_BOT_TOKEN }}
